version: '3.8'

services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - Backend/.env
    volumes:
      - ./Backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
