services:
  backend:
    build:
      context: ./Backend/getting-started-app
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - Backend/.env
    volumes:
      - ./Backend/getting-started-app:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./Frontend/react-app
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
